apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spn-providers-all
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: 'https://github.com/SrFeO3/orchestrator-comparison-lab.git'
    targetRevision: HEAD
    path: k8s/providers-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
