apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-api
  template:
    metadata:
      labels:
        app: provider-api
    spec:
      hostAliases:
      - ip: "10.43.0.100"
        hostnames:
        - "hub1.test.v2.chip-in.net"
      volumes:
      - name: certs
        secret:
          secretName: provider-api-certs

      containers:
      - name: spn-api
        image: ghcr.io/srfeo3/fruitshop-api:latest
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORTS
          value: "7444"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: provider-api-config
              key: DATABASE_URL
        resources:
          limits:
            cpu: 100m
            memory: 256Mi

      - name: spn-provider
        image: ghcr.io/chip-in-v2/spnagent/provider:latest
        env:
        - name: SPN_HUB_HOSTNAME
          value: "hub1.test.v2.chip-in.net"
        - name: SPN_HUB_PORT
          value: "4433"
        - name: FORWARD_ADDRESS
          value: "127.0.0.1:7444"
        - name: SPN_AGENT_TRUST_CERTIFICATE_ROOT
          value: "/etc/ssl/workers/ca-certificates/ca.pem"
        - name: SPN_AGENT_CLIENT_CERTIFICATE
          value: "/etc/ssl/workers/client-certs/client.pem"
        - name: SPN_AGENT_CLIENT_CERTIFICATE_KEY
          value: "/etc/ssl/workers/client-certs/client-key.pem"
        - name: RUST_LOG
          value: "info"
        volumeMounts:
        - name: certs
          mountPath: /etc/ssl/workers/ca-certificates/ca.pem
          subPath: ca.pem
        - name: certs
          mountPath: /etc/ssl/workers/client-certs/client.pem
          subPath: client.pem
        - name: certs
          mountPath: /etc/ssl/workers/client-certs/client-key.pem
          subPath: client-key.pem
          readOnly: true
