apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../provider-api
  - ../provider-auth
  - ../provider-db
  - ../provider-nginx
  - ../provider-www
  - ../provider-wwwtest