apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../provider-api/deployment.yaml
  - ../provider-auth/deployment.yaml
  - ../provider-db/deployment.yaml
  - ../provider-nginx/deployment.yaml
  - ../provider-www/deployment.yaml
  - ../provider-wwwtest/deployment.yaml