# SPN Gateway Deployment
# External Resource Requirements:
# 1. ConfigMap [spngw-consumer-config]: 
#    - 00-default.conf (Supervisor conf) -> /etc/supervisor/conf.d/
#    - private-ca.crt (Trusted CA)        -> /etc/ssl/workers/ca-certificates/
# 2. ConfigMap [spngw-config]:
#    - pinconfig.yaml -> /app/conf/
# 3. Secret [spngw-consumer-certs]: 
#    - worker-a.crt, worker-a.key (Auth) -> /etc/ssl/workers/client-certs/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spn-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spn-gw
  template:
    metadata:
      labels:
        app: spn-gw
    spec:
      hostAliases:
      - ip: "10.43.0.100"
        hostnames:
        - "hub1.test.v2.chip-in.net"
      containers:
      - name: spngw
        image: ghcr.io/chip-in-v2/spngw:latest
        ports:
        - name: gw-http
          containerPort: 7080
        - name: gw-https
          containerPort: 7443
        env:
        - name: APIGW_INVENTORY_URL
          value: "http://spn-inventory-service:3000/v1"
        - name: APIGW_TLS_BIND_ADDRESS
          value: "0.0.0.0:7443"
        - name: APIGW_HTTP_BIND_ADDRESS
          value: "0.0.0.0:7080"
        - name: APIGW_TLS_REDIRECT_PORT
          value: "443"
        - name: APIGW_PINGORA_CONF
          value: "/app/conf/pinconfig.yaml"
        - name: APIGW_REDIS_URL
          value: "redis://127.0.0.1:6379"
        - name: RUST_LOG
          value: "info"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: gw-http
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: gw-http
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        volumeMounts:
        - name: gw-config
          mountPath: /app/conf/pinconfig.yaml
          subPath: pinconfig.yaml
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
      - name: multi-consumer
        image: ghcr.io/chip-in-v2/spnagent/multi-consumer:latest
        env:
        - name: SPN_HUB_HOSTNAME
          value: "hub1.test.v2.chip-in.net"
        - name: SPN_HUB_PORT
          value: "4433"
        - name: RUST_LOG
          value: "info"
        volumeMounts:
        - name: supervisor-conf
          mountPath: /etc/supervisor/conf.d/
        - name: worker-ca
          mountPath: /etc/ssl/workers/ca-certificates/
        - name: worker-certs
          mountPath: /etc/ssl/workers/client-certs/
      volumes:
      - name: gw-config
        configMap:
          name: spngw-config
      - name: supervisor-conf
        configMap:
          name: spngw-consumer-supervisor-config
      - name: worker-ca
        configMap:
          name: spnagent-trustca-config
      - name: worker-certs
        secret:
          secretName: spngw-consumer-certs
