apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spn-gw-ingress-http
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`www.test.v2.chip-in.net`) || Host(`auth.test.v2.chip-in.net`) || Host(`check.test.v2.chip-in.net`) || Host(`api.test.v2.chip-in.net`) || Host(`sirius.test.v2.chip-in.net`)
    kind: Rule
    services:
    - name: spn-gw-service
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: spn-gw-ingress-passthrough
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`www.test.v2.chip-in.net`) || HostSNI(`auth.test.v2.chip-in.net`) || HostSNI(`check.test.v2.chip-in.net`) || HostSNI(`api.test.v2.chip-in.net`) || HostSNI(`sirius.test.v2.chip-in.net`)
    services:
    - name: spn-gw-service
      port: 443
  tls:
    passthrough: true
