# SPN Inventory PostSync Setup Job
# External Resource Requirements:
# 1. ConfigMap [inventory-setup-script]: Contains setup.sh -> /scripts/setup.sh
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: inventory-setup-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: setup-executor
        image: badouralix/curl-jq:latest
        command: ["/bin/sh", "/scripts/setup.sh"]
        volumeMounts:
        - name: script-vol
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: script-vol
        configMap:
          name: inventory-setup-script
